# Build options for parsers

# No more fake-gyp.py since some idiots do not update their bindings.gyp
# so we may as well as just maintain a set of flags by ourselves
# Additionally, since C++ scanners are deprecated,
# and literally only one language included in nvim-treesitter uses it,
# I will just ignore its existence.

# Fields:
# remote: string?
#     url to the git repository where the parser is hosted
#     may be omitted if only consists of queries from nvim-treesitter
# revision: string = 'HEAD'
#     revision to checkout to
#     can be a branch or tag
# generate: bool = True
#     whether the grammar needs to be generated
# std: string = 'c11'
#     C standard to use
# source_path: string = ''
#     subdirectory containing src/parser.c in the remote repository
# files: [str]
#     list of patterns of filenames to match to this languages

[bash]
remote = 'https://github.com/tree-sitter/tree-sitter-bash'
files = [
	'%.sh$',
	'%.bash$',
	'%.zsh$',
	'%.profile$',
	'%.bashrc$',
	'%.zshrc$'
]

[c]
remote = 'https://github.com/tree-sitter/tree-sitter-c'
files = [ '%.c$' ]

[c_sharp]
remote = 'https://github.com/tree-sitter/tree-sitter-c-sharp'
revision = '88366631d598ce6595ec655ce1591b315cffb14c'
files = [ '%.cs$' ]

[cpp]
remote = 'https://github.com/tree-sitter/tree-sitter-cpp'
files = [
	'%.h$',
	'%.cpp$', '%.hpp$',
	'%.cxx$', '%.hxx$',
	'%.c++$', '%.h++$',
	'%.cc$', '%.hh$',
	'%.inl$',
	'%.C$', '%.H$',
	'%.ino$'
]

[css]
remote = 'https://github.com/tree-sitter/tree-sitter-css'
files = [ '%.css$' ]

[d]
remote = 'https://github.com/gdamore/tree-sitter-d'
files = [ '%.d$', '%.di$' ]

[dockerfile]
remote = 'https://github.com/camdencheek/tree-sitter-dockerfile'
files = [ '[Dd]ockerfile$', '%.dockerfile$' ]

[ecma]

[go]
remote = 'https://github.com/tree-sitter/tree-sitter-go'
files = [ '%.go$' ]

[gomod]
remote = 'https://github.com/camdencheek/tree-sitter-go-mod'
files = [ 'go%.mod$' ]

[gosum]
remote = 'https://github.com/amaanq/tree-sitter-go-sum'
files = [ 'go%.sum$' ]

[html]
remote = 'https://github.com/tree-sitter/tree-sitter-html'
files = [ '%.html?$' ]

[html_tags]

[java]
remote = 'https://github.com/tree-sitter/tree-sitter-java'
files = [ '%.java$' ]

[javascript]
remote = 'https://github.com/tree-sitter/tree-sitter-javascript'
files = [ '%.js$', '%.cjs$', '%.mjs$', '%.jsx$' ]

[jsx]

[json]
remote = 'https://github.com/tree-sitter/tree-sitter-json'
files = [ '%.json$' ]

[julia]
remote = 'https://github.com/tree-sitter/tree-sitter-julia'
files = [ '%.jl$' ]

[kotlin]
remote = 'https://github.com/fwcd/tree-sitter-kotlin'
revision = '93bfeee1555d2b1442d68c44b0afde2a3b069e46'
files = [ '%.kt$', '%.kts$' ]

[lua]
remote = 'https://github.com/MunifTanjim/tree-sitter-lua'
files = [ '%.lua$' ]

[markdown]
remote = 'https://github.com/tree-sitter-grammars/tree-sitter-markdown'
source_path = 'tree-sitter-markdown'
files = [ '%.md$', '%.markdown$' ]

[markdown_inline]
remote = 'https://github.com/tree-sitter-grammars/tree-sitter-markdown'
source_path = 'tree-sitter-markdown-inline'

[php]
remote = 'https://github.com/tree-sitter/tree-sitter-php'
source_path = 'php'
files = [ '%.php$', '%.phtml$' ]

[php_only]
remote = 'https://github.com/tree-sitter/tree-sitter-php'
source_path = 'php_only'

[python]
remote = 'https://github.com/tree-sitter/tree-sitter-python'
files = [ '%.py$', '%.pyw$' ]

[regex]
remote = 'https://github.com/tree-sitter/tree-sitter-regex'

[ruby]
remote = 'https://github.com/tree-sitter/tree-sitter-ruby'
files = [ '%.rb$', '%.rake$', 'Gemfile$', 'Rakefile$' ]

[rust]
remote = 'https://github.com/tree-sitter/tree-sitter-rust'
files = [ '%.rs$' ]

[toml]
remote = 'https://github.com/tree-sitter-grammars/tree-sitter-toml'
files = [ '%.toml$' ]

[tsx]
remote = 'https://github.com/tree-sitter/tree-sitter-typescript'
source_path = 'tsx'
files = [ '%.tsx$' ]

[typescript]
remote = 'https://github.com/tree-sitter/tree-sitter-typescript'
source_path = 'typescript'
files = [ '%.ts$', '%.mts$', '%.cts$' ]

[xml]
remote = 'https://github.com/tree-sitter-grammars/tree-sitter-xml'
source_path = 'xml'
files = [ '%.xml$', '%.xsd$', '%.svg$' ]

[yaml]
remote = 'https://github.com/tree-sitter-grammars/tree-sitter-yaml'
files = [ '%.ya?ml$' ]

[zig]
remote = 'https://github.com/maxxnino/tree-sitter-zig'
files = [ '%.zig$' ]
