name: Generate source packages

on:
  workflow_call:
  workflow_dispatch:

jobs:
  generate:
    name: Generate updated source packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Generate
        run: |
          python3 package_sources.py
          python3 -c "from pathlib import Path; import sys; sys.exit(0 if list(Path('srcpkg').glob('*.zip')) else 'no source packages generated')"
      - name: Upload source packages artifact
        uses: actions/upload-artifact@v4
        with:
          name: srcpkgs
          path: srcpkg/*.zip
      - name: Upload updated metadata artifact
        uses: actions/upload-artifact@v4
        with:
          name: meta-update
          path: |
            lock.json
            manifest.json
